import React, { Component, Fragment } from 'react'

class Privacy extends Component {
  render() {
    return (
      <Fragment>
        <div className='PrivacyCopy'>
            <h4>Last Updated:</h4>
            <p> 08/03/2023. PLEASE READ THE FOLLOWING TERMS OF SERVICE AGREEMENT CAREFULLY. BY ACCESSING OR USING OUR WEBSITE (THE "SITE") OR OUR SERVICES, YOU HEREBY AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS AND ALL TERMS INCORPORATED HEREIN BY REFERENCE. IT IS THE RESPONSIBILITY OF YOU, THE USER, CUSTOMER, OR PROSPECTIVE CUSTOMER TO READ THE TERMS AND CONDITIONS BEFORE PROCEEDING TO USE THIS SITE. IF YOU DO NOT EXPRESSLY AGREE TO ALL OF THE TERMS AND CONDITIONS, THEN PLEASE DO NOT ACCESS OR USE OUR SITE OR OUR SERVICES.</p>
            <p> The present terms and conditions (this "Agreement" or "Terms") is a legal agreement between you and FITNESS NGO 1 LLC (hereinafter " FITNESSnGO"), a company duly organized and validly existing, located at 250 NW Peacock Blvd, Port Saint Lucie, Florida 34986. This Agreement annuls and voids all previous agreements.</p>

            <h4>OVERVIEW</h4>
            <p> The Site (www.fitnessngo.com) is operated by FITNESSnGO. Throughout the Site, the terms "we", "us" and "our" refer to FITNESSnGO. FITNESSnGO offers this Site, including all information, tools and services available from this Site to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here. By visiting our Site and/or purchasing something from us, you engage in our "Service" and agree to be bound by the following terms and conditions, including those additional terms and conditions and policies referenced herein and/or available by hyperlink. These Terms apply to all users of the Site, including without limitation users who are browsers, vendors, customers, merchants, and/or contributors of content. In the event of an inconsistency between this Agreement and any additional terms or policies referenced herein, the provisions of the additional terms or policies shall control. Please read these Terms carefully before accessing or using our Site.</p>
            <p> By accessing or using any part of the Site, you agree to be bound by these Terms. If you do not agree to all the Terms of this Agreement, then you may not access the Site or use any Service. If these Terms are considered an offer, acceptance is expressly limited to these Terms. Any new features or tools which are added to the current store shall also be subject to the Terms. You can review the most current version of the Terms at any time on this page. We reserve the right to update, change or replace any part of these Terms by posting updates and/or changes to our Site. It is your responsibility to check this page periodically for changes. Your continued use of or access to the Site following the posting of any changes constitutes acceptance of those changes.</p>

            <h4>SECTION 1 - GENERAL TERMS</h4>
            <h6>By agreeing to these Terms, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this Site. You may not use our products or Site for any illegal or unauthorized purpose nor may you, in the use of our products or Site, violate any laws in your jurisdiction (including but not limited to motor vehicle laws). You must not transmit any worms or viruses or any code of a destructive nature. A breach or violation of any of the Terms will result in an immediate termination of your account and right to use our Service. We have the right, but not the obligation, to take any of the following actions in our sole discretion at any time and for any reason without giving you any prior notice:</h6>
            <p>You agree that we will not be liable to you or any third party for taking any of these actions.</p>
            <p>You understand and agree that our Site may include communications such as service announcements and administrative or legal notices from us. Please note that you cannot opt out of receiving these notices.</p>
            <p>You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks.</p>
            <p>You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Site, use of the Site, or access to the Site or any contact on the Site, without express written permission by us.</p>
            <p>You may not modify, publish, transmit, reverse engineer, participate in the transfer or sale, create derivative works, or in any way exploit any of the content, in whole or in part, found on the Site. FITNESSnGO content is not for resale. Use of the Site does not entitle users to make any unauthorized use of any protected content, and in particular you will not delete or alter any proprietary rights or attribution notices in any content. You will use protected content solely for your personal use, and will make no other use of the content without the express written permission of FITNESSnGO and the copyright owner. You agree that you do not acquire any ownership rights in any protected content. We do not grant you any licenses, express or implied, to the intellectual property of FITNESSnGO or our licensors except as expressly authorized by these Terms.</p>
            <h4>SECTION 2 - CREATING AN ACCOUNT</h4>
            <p>Once you create an account with us, you are registered on the FITNESSnGO Site. The terms "member," "membership," and "account" all refer to this registration as a member on FITNESSnGO's Site. If you are merely surfing or browsing through the Site and have not yet created an account, your use of the Site is still subject to this Agreement; if you do not agree to this Agreement, do not use the Site.</p>
            <p>When you create an account, you will provide a unique username and email. We will also ask you to create a password. Because any activities that occur under your username or password are your responsibility it is important for you to keep your username and/or password secure. You may not assign or otherwise transfer your account to any other person or entity. You acknowledge that FITNESSnGO is not responsible for third party access to your account that results from theft or misappropriation of your account. Notify us immediately if you believe that someone has used your username, email, or password without your authorization.</p>
            <h6>Furthermore, the registering party hereby acknowledges, understands and agrees to:</h6>
            <p>a) furnish factual, correct, current and complete information with regards to yourself as may be requested by the data registration process, and</p>
            <p>b) maintain and promptly update your registration and profile information in an effort to maintain accuracy and completeness at all times.</p>
            <p>If anyone knowingly provides any information of a false, untrue, inaccurate or incomplete nature, FITNESS NGO 1 LLC will have sufficient grounds and rights to suspend or terminate the member in violation of this aspect of the Agreement, and as such refuse any and all current or future use of FITNESS NGO 1 LLC Services, or any portion thereof.</p>
            <h4>SECTION 3 - CONDUCT</h4>
            <p>As a user or member of the Site, you herein acknowledge, understand and agree that all information, text, software, data, photographs, music, video, messages, tags or any other content, whether it is publicly or privately posted and/or transmitted, is the expressed sole responsibility of the individual from whom the content originated. In short, this means that you are solely responsible for any and all content posted, uploaded, emailed, transmitted or otherwise made available by way of the FITNESSnGO Services, and as such, we do not guarantee the accuracy, integrity or quality of such content. It is expressly understood that by use of our Services, you may be exposed to content including, but not limited to, any errors or omissions in any content posted, and/or any loss or damage of any kind incurred as a result of the use of any content posted, emailed, transmitted or otherwise made available by FITNESSnGO.</p>
            <h6>Furthermore, you herein agree not to make use of FITNESS NGO 1 LLC's Services for the purpose of:</h6>
            <p>a) uploading, posting, emailing, transmitting, or otherwise making available any content that shall be deemed unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, or invasive of another's privacy or which is hateful, and/or racially, ethnically, or otherwise objectionable;</p>
            <p>b) causing harm to minors in any manner whatsoever;</p>
            <p>c) impersonating any individual or entity, including, but not limited to, any FITNESSnGO officials, forum leaders, guides or hosts or falsely stating or otherwise misrepresenting any affiliation with an individual or entity;</p>
            <p>d) forging captions, headings or titles or otherwise offering any content that you personally have no right to pursuant to any law nor having any contractual or fiduciary relationship with;</p>
            <p>e) uploading, posting, emailing, transmitting or otherwise offering any such content that may infringe upon any patent, copyright, trademark, or any other proprietary or intellectual rights of any other party;</p>
            <p>f) uploading, posting, emailing, transmitting or otherwise offering any content that you do not personally have any right to offer pursuant to any law or in accordance with any contractual or fiduciary relationship;</p>
            <p>g) uploading, posting, emailing, transmitting, or otherwise offering any unsolicited or unauthorized advertising, promotional flyers, "junk mail," "spam," or any other form of solicitation, except in any such areas that may have been designated for such purpose;</p>
            <p>h) uploading, posting, emailing, transmitting, or otherwise offering any source that may contain a software virus or other computer code, any files and/or programs which have been designed to interfere, destroy and/or limit the operation of any computer software, hardware, or telecommunication equipment;</p>
            <p>i) disrupting the normal flow of communication, or otherwise acting in any manner that would negatively affect other users' ability to participate in any real time interactions;</p>
            <p>k) intentionally or unintentionally violating any local, state, federal, national or international law, including, but not limited to, rules, guidelines, and/or regulations decreed by the U.S. Securities and Exchange Commission, in addition to any rules of any nation or other securities exchange, that would include without limitation, the New York Stock Exchange, the American Stock Exchange, or the NASDAQ, and any regulations having the force of law;</p>
            <p>l) providing informational support or resources, concealing and/or disguising the character, location, and or source to any organization delegated by the United States government as a "foreign terrorist organization" in accordance to Section 219 of the Immigration Nationality Act;</p>
            <p>m) "stalking" or with the intent to otherwise harass another individual; and/or</p>
            <p>n) collecting or storing of any personal data relating to any other member or user in connection with the prohibited conduct and/or activities which have been set forth in the aforementioned paragraphs.</p>
            <h6>FITNESS NGO 1 LLC herein reserves the right to pre-screen, refuse and/or delete any content currently available through our Services. In addition, we reserve the right to remove and/or delete any such content that would violate the Terms or which would otherwise be considered offensive to other visitors, users and/or members.</h6>
            <h6>FITNESS NGO 1 LLC herein reserves the right to access, preserve and/or disclose member account information and/or content if it is requested to do so by law or in good faith belief that any such action is deemed reasonably necessary for:</h6>
            <p>a) compliance with any legal process;</p>
            <p>b) enforcement of the Terms;</p>
            <p>c) responding to any claim that therein contained content is in violation of the rights of any third party;</p>
            <p>d) responding to requests for customer service; or</p>
            <p>e) protecting the rights, property or the personal safety of FITNESS NGO 1 LLC, its visitors, users and members, including the general public.</p>
            <p>FITNESS NGO 1 LLC herein reserves the right to include the use of security components that may permit digital information or material to be protected, and that such use of information and/or material is subject to usage guidelines and regulations established by FITNESS NGO 1 LLC or any other content providers supplying content services to FITNESS NGO 1 LLC. You are hereby prohibited from making any attempt to override or circumvent any of the embedded usage rules in our Services. Furthermore, unauthorized reproduction, publication, distribution, or exhibition of any information or materials supplied by our Services, despite whether done so in whole or in part, is expressly prohibited.</p>
            <h4>SECTION 4 - GLOBAL USE; EXPORT/IMPORT COMPLIANCE</h4>
            <p>
                Due to the global nature of the internet, through the use of our network you hereby agree to comply with all local rules relating to online conduct and that which is considered acceptable content. Uploading, posting and/or transferring of software, technology and other technical data may be subject to the export and import laws of the United States and possibly other countries. Through the use of our network, you thus agree to comply with all applicable export and import laws, statutes and regulations, including, but not limited to, the Export Administration Regulations (http://www.access.gpo.gov/bis/ear/ear_data.html), as well as the sanctions control program of the United States (http://www.treasury.gov/resource-center/sanctions/Programs/Pages/Programs.aspx). Furthermore, you state and pledge that you:
                <br></br><br></br>
                a) are not on the list of prohibited individuals which may be identified on any government export exclusion report (http://www.bis.doc.gov/complianceandenforcement/liststocheck.htm) nor a member of any other government which may be part of an export-prohibited country identified in applicable export and import laws and regulations;
                <br></br><br></br>
                b) agree not to transfer any software, technology or any other technical data through the use of our network Services to any export-prohibited country;
                <br></br><br></br>
                c) agree not to use our website network Services for any military, nuclear, missile, chemical or biological weaponry end uses that would be a violation of the U.S. export laws; and
                <br></br><br></br>
                d) agree not to post, transfer nor upload any software, technology or any other technical data which would be in violation of the U.S. or other applicable export and/or import laws.
            </p>
            <h4>SECTION 5 - SUBMITTED CONTENT</h4>
            <p>
                 FITNESS NGO 1 LLC shall not lay claim to ownership of any content submitted by any visitor, member, or user, nor make such content available for inclusion on our website Services. Therefore, you hereby grant and allow for FITNESS NGO 1 LLC the below listed worldwide, royalty-free and non-exclusive licenses, as applicable:
                 <br></br><br></br>
                a) The content submitted or made available for inclusion on the publicly accessible areas of FITNESS NGO 1 LLC's Sites, the license provided to permit to use, distribute, reproduce, modify, adapt, publicly perform and/or publicly display said Content on our network Services is for the sole purpose of providing and promoting the specific area to which this content was placed and/or made available for viewing. This license shall be available so long as you are a member of FITNESS NGO 1 LLC's sites, and shall terminate at such time when you elect to discontinue your membership.
                <br></br><br></br>
                b) Photos, audio, video and/or graphics submitted or made available for inclusion on the publicly accessible areas of FITNESS NGO 1 LLC's sites, the license provided to permit to use, distribute, reproduce, modify, adapt, publicly perform and/or publicly display said Content on our network Services are for the sole purpose of providing and promoting the specific area in which this content was placed and/or made available for viewing. This license shall be available so long as you are a member of FITNESS NGO 1 LLC's sites and shall terminate at such time when you elect to discontinue your membership.
                <br></br><br></br>
                c) For any other content submitted or made available for inclusion on the publicly accessible areas of FITNESS NGO 1 LLC's sites, the continuous, binding and completely sub-licensable license which is meant to permit to use, distribute, reproduce, modify, adapt, publish, translate, publicly perform and/or publicly display said content, whether in whole or in part, and the incorporation of any such Content into other works in any arrangement or medium current used or later developed.
                <br></br><br></br>
                Those areas which may be deemed "publicly accessible" areas of FITNESS NGO 1 LLC's Sites are those such areas of our network properties which are meant to be available to the general public, and which would include message boards and groups that are openly available to both users and members. However, those areas which are not open to the public, and thus available to members only, would include our mail system and instant messaging.
                <br></br><br></br>
                CONTRIBUTIONS TO COMPANY WEBSITE
                <br></br><br></br>
                FITNESS NGO 1 LLC may provide an area for our user and members to contribute feedback to our website. When you submit ideas, documents, suggestions and/or proposals ("Contributions") to our site, you acknowledge and agree that:
                <br></br><br></br>
                a) your contributions do not contain any type of confidential or proprietary information;
                <br></br><br></br>
                b) FITNESSnGO shall not be liable or under any obligation to ensure or maintain confidentiality, expressed or implied, related to any Contributions;
                <br></br><br></br>
                c) FITNESSnGO shall be entitled to make use of and/or disclose any such Contributions in any such manner as they may see fit;
                <br></br><br></br>
                d) the contributor's Contributions shall automatically become the sole property of FITNESSnGO; and
                <br></br><br></br>
                e) FITNESSnGO is under no obligation to either compensate or provide any form of reimbursement in any manner or nature.
            </p>
            <h4>SECTION 6 - PRIVACY POLICY</h4>
            <p>Every member's registration data and various other personal information are strictly protected by the FITNESS NGO 1 LLC Online Privacy Policy (see the full Privacy Policy at http://localhost:3000/privacy). As a member, you herein consent to the collection and use of the information provided, including the transfer of information within the United States and/or other countries for storage, processing or use by FITNESS NGO 1 LLC and/or our subsidiaries and affiliates.</p>

        </div>
      </Fragment>
    )
  }
}

export default Privacy